name: my-table-1234-qweqweqew.workflow.yaml
'on': workflow_dispatch
jobs:
  mock-job:
    runs-on: ubuntu-latest
    steps:
    - name: my-step-1
      run: 'echo "Mock job in progress"

        sleep 30'
env:
  workflow_file_name: my-table-1234-qweqweqew.workflow.yaml
  account_nubmer: '1234567890'
  table_name: my-table-1234-qweqweqew
  time_to_take_backup: '123'
  restored_table_retention_days: '7'
  dynamodb_restore_method: manual
  cron: '"0 4 * * *"'
