name: Onboarding workflow
on: workflow_dispatch
permissions:
  contents: write
jobs:
  generate-dynamic-workflow:
    runs-on: ubuntu-latest
    outputs:
      workflow_file_name: ${{ steps.generate-workflow.outputs.workflow_file_name }}
    steps:
      # Checkout the branch
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GHPAT}} #required for github action to commit the file to workflow directory

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate workflow
        id: generate-workflow
        run: |
          python convert.py -o backup -t ondemand

      - name: Setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit and Push new workflow file
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "new workflow file created - ${{steps.generate-workflow.outputs.workflow_file_name}}"
          git push origin main

      - name: Print workflow file output
        env:
          OUTPUT: ${{steps.generate-workflow.outputs.workflow_file_name}}
        run: |
          echo "$OUTPUT"
